export const ROUTES = {
  HOME: '/',
  SIGN_IN: '/sign-in',
  SIGN_UP: '/sign-up',
  AUTH_CALLBACK: '/auth/callback',
  AUTH_CONFIRM: '/auth/confirm',
  DASHBOARD: '/dashboard',
  PROJECT_NEW: '/projects/new',
  PROJECT: (id: string) => `/projects/${id}`,
  PROJECT_OVERVIEW: (id: string) => `/projects/${id}/overview`,
  PROJECT_BRIEF: (id: string) => `/projects/${id}/brief`,
  PROJECT_PRD: (id: string) => `/projects/${id}/prd`,
  PROJECT_ARCHITECTURE: (id: string) => `/projects/${id}/architecture`,
  PROJECT_CONTEXT: (id: string) => `/projects/${id}/context`,
  PROJECT_CHUNKS: (id: string) => `/projects/${id}/chunks`,
  PROJECT_CHUNK: (id: string, chunkId: string) => `/projects/${id}/chunks/${chunkId}`,
  PROJECT_ISSUES: (id: string) => `/projects/${id}/issues`,
  PROJECT_KNOWLEDGE: (id: string) => `/projects/${id}/knowledge`,
  PROJECT_EXPORT: (id: string) => `/projects/${id}/export`,
  PROJECT_SETTINGS: (id: string) => `/projects/${id}/settings`,
  USER_SETTINGS: '/settings',
} as const;
