import { z } from 'zod';

export const ClarifyingQuestionSchema = z.object({
  /** Stable id for the question, generated by the model. Used as form field key. */
  id: z.string().min(1).max(40),
  /** The question text shown to the user. */
  text: z.string().min(5).max(500),
  /** Optional category for grouping. */
  category: z
    .enum(['problem', 'users', 'scope', 'features', 'tech', 'success_criteria', 'other'])
    .optional(),
  /** Optional placeholder/example to guide the user's answer. */
  example: z.string().max(300).optional(),
});

export const ClarifyingQuestionsResponseSchema = z.object({
  questions: z.array(ClarifyingQuestionSchema).min(5).max(10),
});

export type ClarifyingQuestion = z.infer<typeof ClarifyingQuestionSchema>;
export type ClarifyingQuestionsResponse = z.infer<
  typeof ClarifyingQuestionsResponseSchema
>;

/** Input the Edge Function expects from the frontend. */
export const GenerateClarifyingQuestionsInputSchema = z.object({
  projectId: z.string().uuid(),
});

export type GenerateClarifyingQuestionsInput = z.infer<
  typeof GenerateClarifyingQuestionsInputSchema
>;
