import { z } from 'zod';

export const PrdFeaturePrioritySchema = z.enum([
  'must_have',
  'should_have',
  'nice_to_have',
]);
export type PrdFeaturePriority = z.infer<typeof PrdFeaturePrioritySchema>;

export const PrdFeatureSchema = z.object({
  /** Stable id, generated by the model. Used for per-section regeneration in Chunk 14. */
  id: z.string().min(1).max(40),
  name: z.string().min(2).max(200),
  description: z.string().min(10).max(1500),
  priority: PrdFeaturePrioritySchema,
});
export type PrdFeature = z.infer<typeof PrdFeatureSchema>;

export const PrdUserStorySchema = z.object({
  id: z.string().min(1).max(40),
  persona: z.string().min(2).max(200),
  story: z.string().min(10).max(1000),
  acceptance_criteria: z.array(z.string().min(3).max(500)).min(1).max(15),
});
export type PrdUserStory = z.infer<typeof PrdUserStorySchema>;

export const PrdContentSchema = z.object({
  goal: z.string().min(20).max(2000),
  target_users: z.array(z.string().min(3).max(500)).min(1).max(15),
  problem_statement: z.string().min(20).max(3000),
  success_criteria: z.array(z.string().min(3).max(500)).min(1).max(15),
  features: z.array(PrdFeatureSchema).min(1).max(50),
  user_stories: z.array(PrdUserStorySchema).max(30),
  out_of_scope: z.array(z.string().min(3).max(300)).max(25),
  open_questions: z.array(z.string().min(3).max(500)).max(15),
});

export type PrdContent = z.infer<typeof PrdContentSchema>;

/** Combined model output: structured object + Markdown rendering. */
export const PrdModelOutputSchema = z.object({
  content_json: PrdContentSchema,
  content_markdown: z.string().min(100).max(40000),
});
export type PrdModelOutput = z.infer<typeof PrdModelOutputSchema>;

/** Edge Function input. */
export const GeneratePrdInputSchema = z.object({
  projectId: z.string().uuid(),
});
export type GeneratePrdInput = z.infer<typeof GeneratePrdInputSchema>;
